FROM osrf/ros:noetic-desktop-full
SHELL ["/bin/bash", "-c"]
ENV DEBIAN_FRONTEND=noninteractive
ENV ROS_DISTRO=noetic

# Install core ROS packages
RUN apt-get update -y && apt-get install -y --no-install-recommends \
    ros-noetic-tf2-geometry-msgs \
    ros-noetic-ackermann-msgs \
    ros-noetic-joy \
    ros-noetic-map-server \
    && rm -rf /var/lib/apt/lists/*

RUN echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> /etc/bash.bashrc

RUN mkdir -p /workspace/src
RUN apt-get update -y && apt-get install -y --no-install-recommends \
    ros-noetic-teleop-twist-* \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /workspace
CMD ["bash"]
