FROM osrf/ros:jazzy-desktop-full
SHELL ["/bin/bash", "-c"]
ENV DEBIAN_FRONTEND=noninteractive
ENV ROS_DISTRO=jazzy

# Install core ROS2 packages
RUN apt-get update -y && apt-get install -y --no-install-recommends \
    ros-jazzy-tf2-geometry-msgs \
    ros-jazzy-ackermann-msgs \
    ros-jazzy-joy \
    ros-jazzy-nav2-map-server \
    ros-jazzy-nav2-lifecycle-manager \
    ros-jazzy-xacro \
    && rm -rf /var/lib/apt/lists/*

RUN echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> /etc/bash.bashrc

RUN mkdir -p /workspace/src
RUN apt-get update -y && apt-get install -y --no-install-recommends \
    ros-jazzy-teleop-twist-keyboard \
    ros-jazzy-teleop-twist-joy \
    && rm -rf /var/lib/apt/lists/*
RUN apt-get update -y && apt-get install -y --no-install-recommends \
    python3-pip \
    python3-colcon-common-extensions \
    wget \
    && rm -rf /var/lib/apt/lists/*

RUN wget https://repo.anaconda.com/archive/Anaconda3-2025.06-0-Linux-x86_64.sh
RUN bash Anaconda3-2025.06-0-Linux-x86_64.sh -b -p /opt/conda
RUN rm Anaconda3-2025.06-0-Linux-x86_64.sh
ENV PATH="/opt/conda/bin:$PATH"
RUN conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main \
    && conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r
ADD environment.yml .
RUN conda env create -f environment.yml
RUN echo "source activate ros2_env" >> ~/.bashrc
RUN pip3 install torch torchvision --index-url https://download.pytorch.org/whl/cpu
WORKDIR /workspace
CMD ["bash"]
